name: 🐛 Bug Report
description: Report a bug in Summon
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! 🐛

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug and what you expected instead.
      placeholder: "I tried to... but instead..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional info
      description: Screenshots, logs, or anything else that might help
      placeholder: Paste any error messages or attach screenshots...
