name: ✨ Feature Request
description: Suggest a new feature for Summon
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Got an idea? We'd love to hear it! ✨

  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
      placeholder: "I'm frustrated when... / It would be helpful if..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: What would you like to see?
      placeholder: "I'd like to be able to..."
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Feature area
      options:
        - MCP Server Generation
        - OpenAPI Integration
        - AI Playground
        - Tool Management
        - User Interface
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      placeholder: Any mockups, examples, or other details...
