name: ❓ Question
description: Ask a question about Summon
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Need help? Ask away! 🤝

  - type: textarea
    id: question
    attributes:
      label: Your question
      placeholder: "How do I...? / Why does...? / What's the best way to...?"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Topic
      options:
        - Getting Started
        - MCP Server Generation
        - OpenAPI Integration
        - AI Playground
        - Troubleshooting
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      placeholder: "I'm trying to... / My goal is to..."
